// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcvjqyjlnqosnpvzixmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjdmpxeWpsbnFvc25wdnppeG1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNjc5NzEsImV4cCI6MjA3MDk0Mzk3MX0.TDoaPY6YAYoNfA43FNNC2KIUKUGl-BopC12ehcW1EmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});